wandb_version: 1

entropy_coeff:
  desc: null
  value: 2.4615595595739692e-06
lr:
  desc: null
  value: 6.321657363492945e-05
sgd_minibatch_size:
  desc: null
  value: 64
lambda:
  desc: null
  value: 0.3
framework:
  desc: null
  value: torch
model:
  desc: null
  value:
    _disable_preprocessor_api: false
    _disable_action_flattening: false
    fcnet_hiddens:
    - 256
    - 256
    fcnet_activation: tanh
    conv_filters: null
    conv_activation: relu
    post_fcnet_hiddens: []
    post_fcnet_activation: relu
    free_log_std: false
    no_final_linear: false
    vf_share_layers: false
    use_lstm: false
    max_seq_len: 20
    lstm_cell_size: 256
    lstm_use_prev_action: false
    lstm_use_prev_reward: false
    _time_major: false
    use_attention: false
    attention_num_transformer_units: 1
    attention_dim: 64
    attention_num_heads: 1
    attention_head_dim: 32
    attention_memory_inference: 50
    attention_memory_training: 50
    attention_position_wise_mlp_dim: 32
    attention_init_gru_gate_bias: 2.0
    attention_use_n_prev_actions: 0
    attention_use_n_prev_rewards: 0
    framestack: true
    dim: 84
    grayscale: false
    zero_mean: true
    custom_model: null
    custom_model_config: {}
    custom_action_dist: null
    custom_preprocessor: null
    encoder_latent_dim: null
    lstm_use_prev_action_reward: -1
    _use_default_native_models: -1
num_envs_per_worker:
  desc: null
  value: 1000
log_level:
  desc: null
  value: DEBUG
num_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 1
env:
  desc: null
  value: StockTrading_train
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687229124.384947
    t:
      1:
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 8
    framework: torch
trial_log_path:
  desc: null
  value: /home/BL-Project/FINRL_TEST_MLP/FINRL_TEST_MLP/PPO_StockTrading_train_9300f718_1_entropy_coeff=0.0000,env=StockTrading_train,framework=torch,lambda=0.3000,log_level=DEBUG,lr=0.0_2023-06-20_02-45-19
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
num_cpus_per_worker:
  desc: null
  value: 1
num_gpus_per_worker:
  desc: null
  value: 0
_fake_gpus:
  desc: null
  value: false
num_learner_workers:
  desc: null
  value: 0
num_gpus_per_learner_worker:
  desc: null
  value: 0
num_cpus_per_learner_worker:
  desc: null
  value: 1
local_gpu_idx:
  desc: null
  value: 0
custom_resources_per_worker:
  desc: null
  value: {}
placement_strategy:
  desc: null
  value: PACK
eager_tracing:
  desc: null
  value: false
eager_max_retraces:
  desc: null
  value: 20
tf_session_args:
  desc: null
  value:
    intra_op_parallelism_threads: 2
    inter_op_parallelism_threads: 2
    gpu_options:
      allow_growth: true
    log_device_placement: false
    device_count:
      CPU: 1
    allow_soft_placement: true
local_tf_session_args:
  desc: null
  value:
    intra_op_parallelism_threads: 8
    inter_op_parallelism_threads: 8
env_config:
  desc: null
  value: {}
observation_space:
  desc: null
  value: null
action_space:
  desc: null
  value: null
env_task_fn:
  desc: null
  value: null
render_env:
  desc: null
  value: false
clip_rewards:
  desc: null
  value: null
normalize_actions:
  desc: null
  value: true
clip_actions:
  desc: null
  value: false
disable_env_checking:
  desc: null
  value: false
is_atari:
  desc: null
  value: false
auto_wrap_old_gym_envs:
  desc: null
  value: true
sample_collector:
  desc: null
  value: ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector
sample_async:
  desc: null
  value: false
enable_connectors:
  desc: null
  value: true
rollout_fragment_length:
  desc: null
  value: auto
batch_mode:
  desc: null
  value: truncate_episodes
remote_worker_envs:
  desc: null
  value: false
remote_env_batch_wait_ms:
  desc: null
  value: 0
validate_workers_after_construction:
  desc: null
  value: true
preprocessor_pref:
  desc: null
  value: deepmind
observation_filter:
  desc: null
  value: NoFilter
synchronize_filters:
  desc: null
  value: true
compress_observations:
  desc: null
  value: false
enable_tf1_exec_eagerly:
  desc: null
  value: false
sampler_perf_stats_ema_coef:
  desc: null
  value: null
gamma:
  desc: null
  value: 0.99
train_batch_size:
  desc: null
  value: 4000
optimizer:
  desc: null
  value: {}
max_requests_in_flight_per_sampler_worker:
  desc: null
  value: 2
learner_class:
  desc: null
  value: null
_enable_learner_api:
  desc: null
  value: false
_learner_hps:
  desc: null
  value: PPOLearnerHPs(kl_coeff=0.2, kl_target=0.01, use_critic=True, clip_param=0.3,
    vf_clip_param=10.0, entropy_coeff=2.4615595595739692e-06, vf_loss_coeff=1.0, lr_schedule=None,
    entropy_coeff_schedule=None)
explore:
  desc: null
  value: true
exploration_config:
  desc: null
  value:
    type: StochasticSampling
policy_states_are_swappable:
  desc: null
  value: false
input_config:
  desc: null
  value: {}
actions_in_input_normalized:
  desc: null
  value: false
postprocess_inputs:
  desc: null
  value: false
shuffle_buffer_size:
  desc: null
  value: 0
output:
  desc: null
  value: null
output_config:
  desc: null
  value: {}
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
offline_sampling:
  desc: null
  value: false
evaluation_interval:
  desc: null
  value: null
evaluation_duration:
  desc: null
  value: 10
evaluation_duration_unit:
  desc: null
  value: episodes
evaluation_sample_timeout_s:
  desc: null
  value: 180.0
evaluation_parallel_to_training:
  desc: null
  value: false
evaluation_config:
  desc: null
  value: null
off_policy_estimation_methods:
  desc: null
  value: {}
ope_split_batch_by_episode:
  desc: null
  value: true
evaluation_num_workers:
  desc: null
  value: 0
always_attach_evaluation_results:
  desc: null
  value: false
enable_async_evaluation:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
sync_filters_on_rollout_workers_timeout_s:
  desc: null
  value: 60.0
keep_per_episode_custom_metrics:
  desc: null
  value: false
metrics_episode_collection_timeout_s:
  desc: null
  value: 60.0
metrics_num_episodes_for_smoothing:
  desc: null
  value: 100
min_time_s_per_iteration:
  desc: null
  value: null
min_train_timesteps_per_iteration:
  desc: null
  value: 0
min_sample_timesteps_per_iteration:
  desc: null
  value: 0
export_native_model_files:
  desc: null
  value: false
checkpoint_trainable_policies_only:
  desc: null
  value: false
logger_creator:
  desc: null
  value: null
logger_config:
  desc: null
  value: null
log_sys_usage:
  desc: null
  value: true
fake_sampler:
  desc: null
  value: false
seed:
  desc: null
  value: null
worker_cls:
  desc: null
  value: null
ignore_worker_failures:
  desc: null
  value: false
recreate_failed_workers:
  desc: null
  value: false
max_num_worker_restarts:
  desc: null
  value: 1000
delay_between_worker_restarts_s:
  desc: null
  value: 60.0
restart_failed_sub_environments:
  desc: null
  value: false
num_consecutive_worker_failures_tolerance:
  desc: null
  value: 100
worker_health_probe_timeout_s:
  desc: null
  value: 60
worker_restore_timeout_s:
  desc: null
  value: 1800
rl_module_spec:
  desc: null
  value: null
_enable_rl_module_api:
  desc: null
  value: false
_validate_exploration_conf_and_rl_modules:
  desc: null
  value: true
_tf_policy_handles_more_than_one_loss:
  desc: null
  value: false
_disable_preprocessor_api:
  desc: null
  value: false
_disable_action_flattening:
  desc: null
  value: false
_disable_execution_plan_api:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
replay_sequence_length:
  desc: null
  value: null
horizon:
  desc: null
  value: -1
soft_horizon:
  desc: null
  value: -1
no_done_at_end:
  desc: null
  value: -1
lr_schedule:
  desc: null
  value: null
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
kl_coeff:
  desc: null
  value: 0.2
num_sgd_iter:
  desc: null
  value: 30
shuffle_sequences:
  desc: null
  value: true
vf_loss_coeff:
  desc: null
  value: 1.0
entropy_coeff_schedule:
  desc: null
  value: null
clip_param:
  desc: null
  value: 0.3
vf_clip_param:
  desc: null
  value: 10.0
grad_clip:
  desc: null
  value: null
kl_target:
  desc: null
  value: 0.01
vf_share_layers:
  desc: null
  value: -1
__stdout_file__:
  desc: null
  value: null
__stderr_file__:
  desc: null
  value: null
input:
  desc: null
  value: sampler
multiagent:
  desc: null
  value:
    policies:
      default_policy:
      - null
      - null
      - null
      - null
    policy_mapping_fn: ray.rllib.algorithms.algorithm_config.AlgorithmConfig.DEFAULT_POLICY_MAPPING_FN
    policies_to_train: null
    policy_map_capacity: 100
    policy_map_cache: -1
    count_steps_by: env_steps
    observation_fn: null
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
num_cpus_for_driver:
  desc: null
  value: 1
trial_id:
  desc: null
  value: 9300f718
date:
  desc: null
  value: 2023-06-20_02-47-27
pid:
  desc: null
  value: 6242
hostname:
  desc: null
  value: 354199f85b5b
node_ip:
  desc: null
  value: 172.17.0.3
